version: '3.9'
services:
  foyer-app:
    image: oualhieya02/foyer-app:latest
    container_name: foyer-app
    ports:
      - "8086:8086"
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - foyer-app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./Foyer2425-main/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - foyer-app

  eureka:
    image: oualhieya02/eureka-server:latest
    container_name: eureka
    ports:
      - "8761:8761"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    restart: always




